# Generated by Django 2.1 on 2018-08-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
